import type { LngLat } from "../core/city/types";

export interface CityPreset {
  id: string;
  name: string;
  /** Neighbourhood the snapshot covers. */
  area: string;
  center: LngLat;
  zoom: number;
  bearing: number;
  /** Snapshot covers center ± this many metres. */
  halfSizeM: number;
}

/**
 * Bundled downtown snapshots (public/cities/<id>.json), generated by
 * `pnpm city:snapshots` from OpenStreetMap via Overpass.
 */
export const CITY_PRESETS: CityPreset[] = [
  {
    id: "paris",
    name: "Paris",
    area: "Louvre / Palais-Royal",
    center: [2.337, 48.862],
    zoom: 16,
    bearing: -20,
    halfSizeM: 600,
  },
  {
    id: "berlin",
    name: "Berlin",
    area: "Potsdamer Platz",
    center: [13.376, 52.5096],
    zoom: 16,
    bearing: -25,
    halfSizeM: 600,
  },
  {
    id: "moscow",
    name: "Moscow",
    area: "Moscow-City",
    center: [37.5395, 55.7494],
    zoom: 15.8,
    bearing: 30,
    halfSizeM: 600,
  },
  {
    id: "long-beach",
    name: "Long Beach",
    area: "Downtown",
    center: [-118.1923, 33.7683],
    zoom: 16,
    bearing: -20,
    halfSizeM: 600,
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    area: "Downtown / Bunker Hill",
    center: [-118.2545, 34.0505],
    zoom: 16,
    bearing: -35,
    halfSizeM: 600,
  },
  {
    id: "san-francisco",
    name: "San Francisco",
    area: "Financial District",
    center: [-122.399, 37.7915],
    zoom: 16,
    bearing: -20,
    halfSizeM: 600,
  },
  {
    id: "boston",
    name: "Boston",
    area: "Financial District",
    center: [-71.0565, 42.3555],
    zoom: 16,
    bearing: -20,
    halfSizeM: 600,
  },
];

export const DEFAULT_CITY_ID = "san-francisco";

export const snapshotUrl = (id: string) => `/cities/${id}.json`;
